# 2.2 数据操作

In [1]:
import torch

torch.manual_seed(0) # 生成随机数用的种子
torch.cuda.manual_seed(0)
print(torch.__version__)

1.2.0


[`torch.manual_seed()`](https://pytorch.org/docs/stable/torch.html#torch._C.Generator.manual_seed)的作用是设置用于生成随机数的种子。
[`torch.cuda.manual_seed()`](https://pytorch.org/docs/stable/cuda.html#torch.cuda.manual_seed)作用与`torch.manual_seed()`相同，只不过是在当前GPU上执行，如果不可执行，比如根本就没有GPU，那么它也不报错。

## 2.2.1 创建`Tensor`

创建一个5x3的未初始化的`Tensor`：

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[1.0102e-38, 8.4490e-39, 9.6428e-39],
        [9.6429e-39, 1.0194e-38, 9.1837e-39],
        [4.6837e-39, 9.9184e-39, 9.0000e-39],
        [1.0561e-38, 1.0653e-38, 4.1327e-39],
        [8.9082e-39, 9.8265e-39, 9.4592e-39]])


创建一个5x3的随机初始化的`Tensor`:



In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939]])


创建一个5x3的long型全0的`Tensor`:



In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


直接根据数据创建:

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


还可以通过现有的`Tensor`来创建，此方法会默认重用输入`Tensor`的一些属性，例如数据类型，除非自定义数据类型。

In [47]:
x = x.new_ones(5, 3, dtype=torch.float64)      # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 指定新的数据类型
print(x)                                    

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.1922,  0.5196,  0.6670],
        [-0.7107,  0.2771,  1.2262],
        [ 1.1267,  0.3797, -0.1199],
        [-0.9512, -1.1666,  0.3903],
        [ 0.3792,  1.6658,  0.2601]])


In [7]:
torch.randint(3, 10, (2, 2))

tensor([[7, 7],
        [8, 9]])

In [8]:
torch.normal(0, 1, size=(3, 4))

tensor([[ 2.3466,  1.2333, -0.1832, -1.3140],
        [-1.6894,  1.2525, -0.5545,  0.3019],
        [ 1.1295,  1.7179, -0.8507, -0.8486]])

In [9]:
torch.randn(3,4)

tensor([[-0.1848, -1.1938, -0.2233, -1.2706],
        [ 0.0193,  0.8868,  0.0552,  0.6880],
        [ 1.2326,  1.1580,  0.1673, -1.5773]])

我们可以通过`shape`或者`size()`来获取`Tensor`的形状:

In [10]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


> 注意：返回的torch.Size其实就是一个tuple, 支持所有tuple的操作。

In [11]:
x1 = torch.arange(1., 8) 
print(x1) 
x2= torch.arange(12) 
print(x2)

tensor([1., 2., 3., 4., 5., 6., 7.])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


## 2.2.2 操作
### 算术操作
* **加法形式一**

In [12]:
torch.randint(0,3,(2,3,4))

tensor([[[1, 2, 0, 1],
         [0, 2, 0, 0],
         [2, 2, 2, 2]],

        [[1, 2, 2, 1],
         [0, 1, 0, 1],
         [0, 0, 1, 1]]])

In [13]:
x=torch.randint(0,3,(5,3))
print(x)
y = torch.randint(0,2,(5, 3))
print(y)
print(x + y)

tensor([[1, 1, 2],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 2],
        [1, 2, 2]])
tensor([[0, 0, 1],
        [1, 0, 0],
        [1, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])
tensor([[1, 1, 3],
        [2, 1, 1],
        [2, 1, 2],
        [2, 2, 3],
        [1, 2, 2]])


* **加法形式二**

In [14]:
print(torch.add(x, y))

tensor([[1, 1, 3],
        [2, 1, 1],
        [2, 1, 2],
        [2, 2, 3],
        [1, 2, 2]])


In [15]:
result = torch.empty((5, 3), dtype=torch.int64)
print(result)
print(x)
print(y)
torch.add(x, y, out=result)
print(result)

tensor([[              0,               0,               0],
        [              0,               0,               0],
        [              0,               0,               2],
        [140736222534752,               0,               0],
        [              0,               0,               0]])
tensor([[1, 1, 2],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 2],
        [1, 2, 2]])
tensor([[0, 0, 1],
        [1, 0, 0],
        [1, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])
tensor([[1, 1, 3],
        [2, 1, 1],
        [2, 1, 2],
        [2, 2, 3],
        [1, 2, 2]])


* **加法形式三、inplace**

In [16]:
# adds x to y
y.add_(x)
print(y)

tensor([[1, 1, 3],
        [2, 1, 1],
        [2, 1, 2],
        [2, 2, 3],
        [1, 2, 2]])


> **注：PyTorch操作inplace版本都有后缀"_", 例如`x.copy_(y), x.t_()`**

#### 按元素乘法：

In [17]:
print(x)
print(y)
print(x*y)
print(x*2)

tensor([[1, 1, 2],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 2],
        [1, 2, 2]])
tensor([[1, 1, 3],
        [2, 1, 1],
        [2, 1, 2],
        [2, 2, 3],
        [1, 2, 2]])
tensor([[1, 1, 6],
        [2, 1, 1],
        [2, 1, 2],
        [2, 2, 6],
        [1, 4, 4]])
tensor([[2, 2, 4],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 4],
        [2, 4, 4]])


#### 按元素除法：

In [18]:
test_divide_x = (x+1).to(dtype=torch.float64)
print(test_divide_x)
test_divide_y = (y+1).to(dtype=torch.float64)
print(test_divide_y)
print(test_divide_x/test_divide_y)

tensor([[2., 2., 3.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 3.],
        [2., 3., 3.]], dtype=torch.float64)
tensor([[2., 2., 4.],
        [3., 2., 2.],
        [3., 2., 3.],
        [3., 3., 4.],
        [2., 3., 3.]], dtype=torch.float64)
tensor([[1.0000, 1.0000, 0.7500],
        [0.6667, 1.0000, 1.0000],
        [0.6667, 1.0000, 0.6667],
        [0.6667, 0.6667, 0.7500],
        [1.0000, 1.0000, 1.0000]], dtype=torch.float64)


#### 减法：

In [48]:
print(x)
print(y)
print(x-y)

tensor([[ 0.1922,  0.5196,  0.6670],
        [-0.7107,  0.2771,  1.2262],
        [ 1.1267,  0.3797, -0.1199],
        [-0.9512, -1.1666,  0.3903],
        [ 0.3792,  1.6658,  0.2601]])
tensor([4, 6])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

#### 按元素做指数运算：

In [20]:
print(x)
e=x.to(dtype=torch.float64)#把x转换成浮点
e.exp()

tensor([[1, 1, 2],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 2],
        [1, 2, 2]])


tensor([[2.7183, 2.7183, 7.3891],
        [2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 7.3891],
        [2.7183, 7.3891, 7.3891]], dtype=torch.float64)

#### 矩阵乘法：

In [21]:
print(x)
print(y)
print(y.T)
print(y.shape)
print(y.T.shape)
torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1]))
print(torch.matmul(x,y.T))

tensor([[1, 1, 2],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 2],
        [1, 2, 2]])
tensor([[1, 1, 3],
        [2, 1, 1],
        [2, 1, 2],
        [2, 2, 3],
        [1, 2, 2]])
tensor([[1, 2, 2, 2, 1],
        [1, 1, 1, 2, 2],
        [3, 1, 2, 3, 2]])
torch.Size([5, 3])
torch.Size([3, 5])
tensor([[ 8,  5,  7, 10,  7],
        [ 5,  4,  5,  7,  5],
        [ 5,  4,  5,  7,  5],
        [ 8,  5,  7, 10,  7],
        [ 9,  6,  8, 12,  9]])


#### 矩阵的联结：

In [22]:
print(x)
print(y)
print(torch.cat((x,y),0))
torch.cat((x,y),1)

tensor([[1, 1, 2],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 2],
        [1, 2, 2]])
tensor([[1, 1, 3],
        [2, 1, 1],
        [2, 1, 2],
        [2, 2, 3],
        [1, 2, 2]])
tensor([[1, 1, 2],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 2],
        [1, 2, 2],
        [1, 1, 3],
        [2, 1, 1],
        [2, 1, 2],
        [2, 2, 3],
        [1, 2, 2]])


tensor([[1, 1, 2, 1, 1, 3],
        [1, 1, 1, 2, 1, 1],
        [1, 1, 1, 2, 1, 2],
        [1, 1, 2, 2, 2, 3],
        [1, 2, 2, 1, 2, 2]])

####   判断：

In [23]:
x == y

tensor([[ True,  True, False],
        [False,  True,  True],
        [False,  True, False],
        [False, False, False],
        [ True,  True,  True]])

#### 求和：

In [24]:
x.sum()

tensor(19)

#### 范数：

In [25]:
a = torch.arange(9, dtype= torch.float) - 4
print(a)
b = a.reshape((3, 3))
print(b)
torch.norm(a)

tensor([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])
tensor([[-4., -3., -2.],
        [-1.,  0.,  1.],
        [ 2.,  3.,  4.]])


tensor(7.7460)

In [46]:
print(x)
test_norm_x = x.to(dtype= torch.float)
print(test_norm_x)
print(torch.norm(test_norm_x))
print(torch.norm(test_norm_x,p=1,dim=0))
print(torch.norm(test_norm_x,p=1,dim=1))
print(torch.norm(test_norm_x).item())

tensor([1, 2])
tensor([1., 2.])
tensor(2.2361)
tensor(3.)


IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [44]:
a = torch.arange(12)
print(a)
print(a.shape)
b = a.view(2,2,3)
print(b)
print(b[1,1,2])
print(torch.norm(b.to(dtype=torch.float64), p=1, dim=1))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
tensor(11)
tensor([[ 3.,  5.,  7.],
        [15., 17., 19.]], dtype=torch.float64)


#### 索引

在`Tensor`中，索引（index）代表了元素的位置。`Tensor`的索引从0（第1）开始逐一递增。例如，一个3行2列的矩阵的行索引分别为0、1和2，列索引分别为0和1。

在下面的例子中，我们指定了`Tensor`的行索引截取范围`[1:4]`。依据**左闭右开**（数学表示成\[1,4)）指定范围的惯例，它截取了矩阵`X`中行索引为1和3（即第2到第4行）的两行。

这种与类似NumPy的索引方式，也可以用来操作来访问`Tensor`的一部分，需要注意的是：**索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。**

In [45]:
print(x) # x是一个5*3的数组
print(x[3,2]) # 第4行，第3列的元素
print(x[1:4, :]) # 第2行和第5行
y = x[0, :] # 第1行的所有元素
y += 1
print(y)
print(x[0, :]) # 源tensor也被改了
print(x)

tensor([1, 2])


IndexError: too many indices for tensor of dimension 1

### 改变形状
用`view()`来改变`Tensor`的形状：

In [29]:
y = x.view(15)
z = x.view(-1, 5)  # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


**注意`view()`返回的新tensor与源tensor共享内存，也即更改其中的一个，另外一个也会跟着改变。**

In [30]:
x += 1
print(x)
print(y) # 也加了1

tensor([[3, 3, 4],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 3],
        [2, 3, 3]])
tensor([3, 3, 4, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 3])


如果不想共享内存，推荐先用`clone`创造一个副本然后再使用`view`。

In [31]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[2, 2, 3],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 2],
        [1, 2, 2]])
tensor([3, 3, 4, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 3])


另外一个常用的函数就是`item()`, 它可以将一个标量`Tensor`转换成一个Python number：

In [32]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.0689])
1.0688859224319458


## 2.2.3 广播机制

In [33]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


## 2.2.4 运算的内存开销

In [34]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before)

False


In [35]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before)

True


In [36]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y) == id_before)

True


## 2.2.5 `Tensor`和NumPy相互转换
**`numpy()`和`from_numpy()`这两个函数产生的`Tensor`和NumPy array实际是使用的相同的内存，改变其中一个时另一个也会改变！！！**
### `Tensor`转NumPy

In [37]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


### NumPy数组转`Tensor`

In [38]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


直接用`torch.tensor()`将NumPy数组转换成`Tensor`，该方法总是会进行数据拷贝，返回的`Tensor`和原来的数据不再共享内存。

In [39]:
# 用torch.tensor()转换时不会共享内存
c = torch.tensor(a)
a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


## 2.2.6 `Tensor` on GPU

In [40]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型