# 4.6 GPU计算

到目前为止，我们一直在使用CPU计算。对复杂的神经网络和大规模的数据来说，使用CPU来计算可能不够高效。在本节中，我们将介绍如何使用单块NVIDIA GPU来计算。首先，需要确保已经安装好了至少一块NVIDIA GPU。然后，下载CUDA并按照提示设置好相应的路径（可参考附录中[“使用阿里云运行代码”](../chapter11_appendix/11.04_cloud.ipynb)一节）。这些准备工作都完成后，下面就可以通过`nvidia-smi`命令来查看显卡信息了。

In [1]:
!nvidia-smi # 对Linux/macOS用户有效

Sat Nov  9 16:36:05 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:21:01.0 Off |                    0 |
| N/A   33C    P0    37W / 300W |   2176MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [2]:
import torch
from torch import nn

print(torch.__version__)

1.3.0


## 4.6.1 计算设备

In [3]:
torch.cuda.is_available() # cuda是否可用

True

In [4]:
torch.cuda.device_count() # gpu数量

1

In [5]:
torch.cuda.current_device() # 当前设备索引, 从0开始

0

In [6]:
torch.cuda.get_device_name(0) # 返回gpu名字

'Tesla V100-SXM2-16GB'

## 4.6.2 `Tensor`的GPU计算

In [7]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [8]:
# x = x.cuda(0)
x = x.to('cuda')
x

tensor([1, 2, 3], device='cuda:0')

In [9]:
x.device

device(type='cuda', index=0)

In [10]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.tensor([1, 2, 3], device=device)
# or
x = torch.tensor([1, 2, 3]).to(device)
x

tensor([1, 2, 3], device='cuda:0')

In [11]:
y = x**2
y

tensor([1, 4, 9], device='cuda:0')

In [12]:
# z = y + x.cpu()

## 4.6.3 模型的GPU计算

In [13]:
net = nn.Linear(3, 1)
list(net.parameters())[0].device

device(type='cpu')

In [14]:
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)

In [15]:
x = torch.rand(2,3).cuda()
net(x)

tensor([[-0.2939],
        [-0.3902]], device='cuda:0', grad_fn=<AddmmBackward>)

## 小结

* PyTorch可以指定用来存储和计算的设备，如使用内存的CPU或者使用显存的GPU。在默认情况下，PyTorch会将数据创建在内存，然后利用CPU来计算。
* PyTorch要求计算的所有输入数据都在内存或同一块显卡的显存上。

## 练习

* 试试大一点儿的计算任务，如大矩阵的乘法，看看使用CPU和GPU的速度区别。如果是计算量很小的任务呢？
* GPU上应如何读写模型参数？


## 参考文献

[1] CUDA下载地址。 https://developer.nvidia.com/cuda-downloads