In [1]:
%matplotlib inline


What is PyTorch?【PyTorch简介】
============================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors【张量】
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [3]:
from __future__ import print_function
import torch

<div class="alert alert-info"><h4>Note【未初始化矩阵】</h4><p>An uninitialized matrix is declared,
    but does not contain definite known
    values before it is used. When an
    uninitialized matrix is created,
    whatever values were in the allocated
    memory at the time will appear as the initial values.</p></div>



Construct a 5x3 matrix, uninitialized:



In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


Construct a randomly initialized matrix:【随机数矩阵】



In [8]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0706, 0.2197, 0.1725],
        [0.7586, 0.2165, 0.9523],
        [0.6021, 0.6243, 0.2966],
        [0.9431, 0.9925, 0.7690],
        [0.4781, 0.6032, 0.6833]])


Construct a matrix filled zeros and of dtype long:
【torch.dtype】：https://pytorch.org/docs/stable/tensor_attributes.html#torch.torch.dtype


In [9]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:【直接创建一个张量】

In [10]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user
【由一个已存在的张量去创建一个新张量】


In [11]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.9683e-01,  5.7029e-01,  1.6066e+00],
        [ 1.2457e+00, -1.3981e+00,  1.8155e-01],
        [-5.5024e-04,  2.2003e-01, -3.0950e-01],
        [ 3.4499e-01, -1.2634e-01, -2.9506e+00],
        [ 1.5725e+00,  1.5063e+00,  4.7864e-01]])


科学记数法的形式是由两个数的乘积组成的。表示为a×10^b（aEb）

Get its size:【获取张量的形状大小】



In [14]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.【矩阵运算】</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1 【矩阵加法】



In [25]:
x = torch.randint(3, 5, (5, 3))
y = torch.randint(2, (5, 3))
print(x)
print(y)
print(x + y)

tensor([[3, 3, 4],
        [4, 4, 3],
        [4, 4, 4],
        [3, 4, 3],
        [3, 3, 4]])
tensor([[1, 0, 1],
        [0, 1, 0],
        [1, 1, 1],
        [0, 1, 0],
        [1, 0, 0]])
tensor([[4, 3, 5],
        [4, 5, 3],
        [5, 5, 5],
        [3, 5, 3],
        [4, 3, 4]])


Addition: syntax 2 【torch.add()】：https://pytorch.org/docs/stable/torch.html#torch.add


In [28]:
print(torch.add(x, y))
print(torch.add(x, 1, y))

tensor([[4, 3, 5],
        [4, 5, 3],
        [5, 5, 5],
        [3, 5, 3],
        [4, 3, 4]])
tensor([[4, 3, 5],
        [4, 5, 3],
        [5, 5, 5],
        [3, 5, 3],
        [4, 3, 4]])


Addition: providing an output tensor as argument



In [41]:
x = torch.rand(5, 3)
print(x)
y = torch.rand(5, 3)
print(y)
print(torch.add(x, y))
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.5229, 0.1233, 0.9396],
        [0.8145, 0.7490, 0.2626],
        [0.3590, 0.4251, 0.5955],
        [0.9824, 0.7877, 0.8401],
        [0.9963, 0.8700, 0.6272]])
tensor([[0.0728, 0.4706, 0.8685],
        [0.5591, 0.1267, 0.4796],
        [0.3089, 0.7920, 0.9171],
        [0.8974, 0.5827, 0.3411],
        [0.9290, 0.8472, 0.5775]])
tensor([[0.5957, 0.5940, 1.8081],
        [1.3736, 0.8756, 0.7422],
        [0.6679, 1.2170, 1.5127],
        [1.8799, 1.3704, 1.1812],
        [1.9253, 1.7173, 1.2047]])
tensor([[0.5957, 0.5940, 1.8081],
        [1.3736, 0.8756, 0.7422],
        [0.6679, 1.2170, 1.5127],
        [1.8799, 1.3704, 1.1812],
        [1.9253, 1.7173, 1.2047]])


Addition: in-place



In [43]:
x = torch.randint(3, 5, (5, 3))
y = torch.randint(2, (5, 3))
print(x)
print(y)
# adds x to y
y.add_(x)
print(y)

tensor([[3, 4, 3],
        [4, 4, 3],
        [4, 3, 3],
        [4, 4, 4],
        [3, 3, 4]])
tensor([[0, 1, 1],
        [1, 0, 0],
        [0, 0, 1],
        [0, 0, 1],
        [1, 1, 1]])
tensor([[3, 5, 4],
        [5, 4, 3],
        [4, 3, 4],
        [4, 4, 5],
        [4, 4, 5]])


 <div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!【获取x的第1（下标为0）列】



In [47]:
print(x[:, 0])

tensor([3, 4, 4, 4, 3])


Resizing【改变张量形状】: If you want to resize/reshape tensor, you can use ``torch.view``:



In [50]:
x = torch.randn(4, 4)
print(x)
y = x.view(16)
print(y)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(z)
print(x.size(), y.size(), z.size())

tensor([[-1.0192,  0.2842,  1.4595,  0.5467],
        [ 0.7554, -1.1175,  1.0663, -0.1409],
        [ 1.6339,  0.2263, -1.3486,  0.2586],
        [ 0.0101, -0.9496,  1.8247, -0.5738]])
tensor([-1.0192,  0.2842,  1.4595,  0.5467,  0.7554, -1.1175,  1.0663, -0.1409,
         1.6339,  0.2263, -1.3486,  0.2586,  0.0101, -0.9496,  1.8247, -0.5738])
tensor([[-1.0192,  0.2842,  1.4595,  0.5467,  0.7554, -1.1175,  1.0663, -0.1409],
        [ 1.6339,  0.2263, -1.3486,  0.2586,  0.0101, -0.9496,  1.8247, -0.5738]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [51]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.9374])
1.9374208450317383


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

【注意】The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [52]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [53]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [54]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [55]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.【需要有GPU支持】【演示上阿里云】



In [57]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!