In [12]:
import torch

In [13]:
w = torch.tensor([[0.1, 0.5],[-0.3, 0.8]], requires_grad=True)
w

tensor([[ 0.1000,  0.5000],
        [-0.3000,  0.8000]], requires_grad=True)

In [14]:
x = torch.tensor([0.2, 0.4], requires_grad=True)
x

tensor([0.2000, 0.4000], requires_grad=True)

In [15]:
print(x.shape, w.shape)

torch.Size([2]) torch.Size([2, 2])


In [16]:
q = torch.matmul(w, x)
q

tensor([0.2200, 0.2600], grad_fn=<MvBackward>)

In [17]:
f = torch.pow(torch.norm(q), 2)
print(f)

tensor(0.1160, grad_fn=<PowBackward0>)


In [18]:
print(x.requires_grad)

True


In [19]:
print(w.requires_grad)

True


In [20]:
f.backward()

In [21]:
print(x.grad)

tensor([-0.1120,  0.6360])


In [22]:
print(w.grad)

tensor([[0.0880, 0.1760],
        [0.1040, 0.2080]])
