In [1]:
import torch
import torch.nn.functional as F

In [2]:
torch.arange(0, 5)

tensor([0, 1, 2, 3, 4])

In [12]:
x = torch.arange(0, 5) % 3
x

tensor([0, 1, 2, 0, 1])

In [14]:
x = x.to(torch.float)
x

tensor([0., 1., 2., 0., 1.])

In [18]:
x = x.to(torch.long)
x

tensor([0, 1, 2, 0, 1])

In [19]:
F.one_hot( x )

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [1, 0, 0],
        [0, 1, 0]])

In [9]:
torch.normal(0, 0.01, size=(3, 4))

tensor([[-0.0054, -0.0075, -0.0018, -0.0017],
        [ 0.0095, -0.0162,  0.0085,  0.0126],
        [ 0.0046,  0.0017, -0.0056, -0.0041]])