In [1]:
import torch

In [2]:
w = torch.tensor([[0.1, 0.5],[-0.3, 0.8]], requires_grad=True)
w

tensor([[ 0.1000,  0.5000],
        [-0.3000,  0.8000]], requires_grad=True)

In [3]:
print(w.grad)

None


In [4]:
x = torch.tensor([0.2, 0.4], requires_grad=True)
x

tensor([0.2000, 0.4000], requires_grad=True)

In [10]:
print(w.grad)

None


In [11]:
print(x.shape, w.shape)

torch.Size([2]) torch.Size([2, 2])


In [12]:
q = torch.matmul(w, x)
q

tensor([0.2200, 0.2600], grad_fn=<MvBackward>)

In [13]:
print(w.grad)

None


In [14]:
f = torch.pow(torch.norm(q), 2)
print(f)

tensor(0.1160, grad_fn=<PowBackward0>)


In [15]:
print(x.requires_grad)

True


In [16]:
print(w.requires_grad)

True


In [17]:
f.backward()

In [18]:
print(x.grad)

tensor([-0.1120,  0.6360])


In [19]:
print(w.grad)

tensor([[0.0880, 0.1760],
        [0.1040, 0.2080]])


再次开始一个求导过程之前，需要将已有的梯度清零，否则它将以原值参加新的运算，而导致结果不正确。

In [20]:
w.grad.data.zero_()
w.grad

tensor([[0., 0.],
        [0., 0.]])

In [21]:
d = torch.mean(w)
d.backward()
print(w.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])
