![](images/cs231-l4-bp.png)

In [1]:
import torch

In [ ]:
w = torch.tensor([[0.1, 0.5],[-0.3, 0.8]], requires_grad=True)
w

In [ ]:
print(w.grad)

In [ ]:
x = torch.tensor([0.2, 0.4], requires_grad=True)
x

In [ ]:
print(w.grad)

In [ ]:
print(x.shape, w.shape)

In [ ]:
q = torch.matmul(w, x)
q

In [ ]:
print(w.grad)

In [ ]:
f = torch.pow(torch.norm(q), 2)
print(f)

In [ ]:
print(x.requires_grad)

In [ ]:
print(w.requires_grad)

In [ ]:
f.backward()

In [ ]:
print(x.grad)

In [ ]:
print(w.grad)

再次开始一个求导过程之前，需要将已有的梯度清零，否则它将以原值参加新的运算，而导致结果不正确。

In [ ]:
w.grad.data.zero_()
w.grad

In [ ]:
d = torch.mean(w)
d.backward()
print(w.grad)

张量对张量的求导

In [2]:
x = torch.arange(3, dtype=torch.float64)
x

tensor([0., 1., 2.], dtype=torch.float64)

In [3]:
x.requires_grad_(True)

tensor([0., 1., 2.], dtype=torch.float64, requires_grad=True)

In [4]:
y = x + 2
y

tensor([2., 3., 4.], dtype=torch.float64, grad_fn=<AddBackward0>)

In [5]:
z = 2 * y 

In [6]:
z

tensor([4., 6., 8.], dtype=torch.float64, grad_fn=<MulBackward0>)

In [9]:
v = torch.tensor([1.0, 1.0, 1.0], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.1000, 2.0000, 1.0001], dtype=torch.float64)


In [10]:
x.grad

tensor([1.1000, 2.0000, 1.0001], dtype=torch.float64)