In [1]:
import torch

torch.manual_seed(0) # 生成随机数用的种子
torch.cuda.manual_seed(0)
print(torch.__version__)

1.3.0+cpu


In [4]:
x = torch.zeros(2, 3, names=('N', 'C'))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]], names=('N', 'C'))


In [5]:
x.names

('N', 'C')

In [6]:
x = torch.randn(3, names=('D',))
weight = torch.randn(3, names=('D',), requires_grad=True)
loss = (x - weight).abs()
grad_loss = torch.randn(3)
loss.backward(grad_loss)
weight.grad  # Unnamed for now. Will be named in the future

tensor([-0.4033, -0.8380, -0.7193])

In [7]:
weight.grad.zero_()
grad_loss = grad_loss.refine_names('C')
loss = (x - weight).abs()
# Ideally we'd check that the names of loss and grad_loss match but we don't yet.
loss.backward(grad_loss)
weight.grad

..\torch\csrc\autograd\python_engine.cpp:142: UserWarning: Autograd was passed a named grad tensor with dims ['C']. Autograd does not yet support named tensor semantics, so all names will be ignored. In practice all computed gradients will still be correct according to regular tensor semantics.


tensor([-0.4033, -0.8380, -0.7193])