# 数据操作

## 创建`Tensor`

In [2]:
import tensorflow as tf

print(tf.__version__)

2.0.0


In [3]:
x = tf.range(12)
x

<tf.Tensor: id=3, shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

In [4]:
x.shape

TensorShape([12])

In [5]:
tf.size(x)

<tf.Tensor: id=4, shape=(), dtype=int32, numpy=12>

In [6]:
X = tf.reshape(x, [3, 4])
X

<tf.Tensor: id=6, shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [7]:
tf.zeros([2, 3, 4])

<tf.Tensor: id=9, shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [8]:
tf.ones([3, 4])

<tf.Tensor: id=12, shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [9]:
Y = tf.constant([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Y

<tf.Tensor: id=13, shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])>

In [10]:
tf.random.normal([3, 4])

<tf.Tensor: id=19, shape=(3, 4), dtype=float32, numpy=
array([[ 1.1396872 , -0.84905994, -0.31489274, -0.0313027 ],
       [-0.6989973 ,  0.55356884,  2.0972903 ,  0.9792791 ],
       [-0.12446886,  0.44076294, -0.03380769, -1.2061477 ]],
      dtype=float32)>

In [11]:
X + Y

<tf.Tensor: id=20, shape=(3, 4), dtype=int32, numpy=
array([[ 2,  2,  6,  6],
       [ 5,  7,  9, 11],
       [12, 12, 12, 12]])>

In [12]:
X * Y

<tf.Tensor: id=21, shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  8,  9],
       [ 4, 10, 18, 28],
       [32, 27, 20, 11]])>

In [13]:
X / Y

<tf.Tensor: id=24, shape=(3, 4), dtype=float64, numpy=
array([[ 0.  ,  1.  ,  0.5 ,  1.  ],
       [ 4.  ,  2.5 ,  2.  ,  1.75],
       [ 2.  ,  3.  ,  5.  , 11.  ]])>

In [15]:
tf.random.normal([3, 4])

<tf.Tensor: id=32, shape=(3, 4), dtype=float32, numpy=
array([[ 0.49923214, -0.5447081 ,  0.34865957,  1.2332145 ],
       [ 2.0106714 ,  0.6240955 , -1.5199038 ,  0.9153878 ],
       [-0.33583134, -0.7039141 , -1.5394204 , -2.3694372 ]],
      dtype=float32)>

## 运算

In [16]:
X + Y

<tf.Tensor: id=33, shape=(3, 4), dtype=int32, numpy=
array([[ 2,  2,  6,  6],
       [ 5,  7,  9, 11],
       [12, 12, 12, 12]])>

In [17]:
X * Y

<tf.Tensor: id=34, shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  8,  9],
       [ 4, 10, 18, 28],
       [32, 27, 20, 11]])>

In [18]:
X / Y

<tf.Tensor: id=37, shape=(3, 4), dtype=float64, numpy=
array([[ 0.  ,  1.  ,  0.5 ,  1.  ],
       [ 4.  ,  2.5 ,  2.  ,  1.75],
       [ 2.  ,  3.  ,  5.  , 11.  ]])>

In [21]:
tf.math.exp( tf.cast(Y, tf.float64) ) #Y的数据类型需要转换成浮点型

<tf.Tensor: id=39, shape=(3, 4), dtype=float64, numpy=
array([[ 7.3890561 ,  2.71828183, 54.59815003, 20.08553692],
       [ 2.71828183,  7.3890561 , 20.08553692, 54.59815003],
       [54.59815003, 20.08553692,  7.3890561 ,  2.71828183]])>

In [23]:
tf.matmul( X, tf.transpose(Y) )

<tf.Tensor: id=44, shape=(3, 3), dtype=int32, numpy=
array([[ 18,  20,  10],
       [ 58,  60,  50],
       [ 98, 100,  90]])>

In [25]:
tf.concat([X, Y], 0), tf.concat([X, Y], 1)

(<tf.Tensor: id=50, shape=(6, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 2,  1,  4,  3],
        [ 1,  2,  3,  4],
        [ 4,  3,  2,  1]])>,
 <tf.Tensor: id=52, shape=(3, 8), dtype=int32, numpy=
 array([[ 0,  1,  2,  3,  2,  1,  4,  3],
        [ 4,  5,  6,  7,  1,  2,  3,  4],
        [ 8,  9, 10, 11,  4,  3,  2,  1]])>)

In [28]:
tf.cast((X == Y), tf.int32)

<tf.Tensor: id=57, shape=(3, 4), dtype=int32, numpy=
array([[0, 1, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])>

In [29]:
tf.reduce_sum(X)

<tf.Tensor: id=59, shape=(), dtype=int32, numpy=66>

In [36]:
tf.norm(tf.cast(X, tf.float64)).numpy()

22.494443758403985

In [42]:
a = tf.range(3)
A = tf.reshape(a, [3, 1])
b = tf.range(2)
B = tf.reshape(b, [1, 2])
A, B

(<tf.Tensor: id=126, shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]])>,
 <tf.Tensor: id=132, shape=(1, 2), dtype=int32, numpy=array([[0, 1]])>)

In [41]:
A + B

<tf.Tensor: id=120, shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]])>

In [43]:
X[1:3]

<tf.Tensor: id=136, shape=(2, 4), dtype=int32, numpy=
array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [53]:
X[1, 2] = 9 # 这居然报错，是谁设计的? 脑子被门挤了吗? 再见了TF，怪不得没人用了

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment